# Generated by Django 5.0 on 2024-01-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPart',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('part', models.FloatField()),
            ],
            options={
                'db_table': 'area_part',
            },
        ),
        migrations.CreateModel(
            name='AreaPartVacancy',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('part', models.FloatField()),
            ],
            options={
                'db_table': 'area_part_vacancy',
            },
        ),
        migrations.CreateModel(
            name='AreaSalary',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'area_salary',
            },
        ),
        migrations.CreateModel(
            name='AreaSalaryVacancy',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'area_salary_vacancy',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='YearAnalytics',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('count', models.IntegerField()),
                ('salary_vac', models.FloatField()),
                ('count_vac', models.IntegerField()),
            ],
            options={
                'db_table': 'year_analytics',
            },
        ),
        migrations.CreateModel(
            name='YearSkills',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('skill1', models.CharField(max_length=20)),
                ('skill2', models.CharField(max_length=20)),
                ('skill3', models.CharField(max_length=20)),
                ('skill4', models.CharField(max_length=20)),
                ('skill5', models.CharField(max_length=20)),
                ('skill6', models.CharField(max_length=20)),
                ('skill7', models.CharField(max_length=20)),
                ('skill8', models.CharField(max_length=20)),
                ('skill9', models.CharField(max_length=20)),
                ('skill10', models.CharField(max_length=20)),
                ('skill11', models.CharField(max_length=20)),
                ('skill12', models.CharField(max_length=20)),
                ('skill13', models.CharField(max_length=20)),
                ('skill14', models.CharField(max_length=20)),
                ('skill15', models.CharField(max_length=20)),
                ('skill16', models.CharField(max_length=20)),
                ('skill17', models.CharField(max_length=20)),
                ('skill18', models.CharField(max_length=20)),
                ('skill19', models.CharField(max_length=20)),
                ('skill20', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'year_skills',
            },
        ),
        migrations.CreateModel(
            name='YearSkillsVacancy',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('skill1', models.CharField(max_length=20)),
                ('skill2', models.CharField(max_length=20)),
                ('skill3', models.CharField(max_length=20)),
                ('skill4', models.CharField(max_length=20)),
                ('skill5', models.CharField(max_length=20)),
                ('skill6', models.CharField(max_length=20)),
                ('skill7', models.CharField(max_length=20)),
                ('skill8', models.CharField(max_length=20)),
                ('skill9', models.CharField(max_length=20)),
                ('skill10', models.CharField(max_length=20)),
                ('skill11', models.CharField(max_length=20)),
                ('skill12', models.CharField(max_length=20)),
                ('skill13', models.CharField(max_length=20)),
                ('skill14', models.CharField(max_length=20)),
                ('skill15', models.CharField(max_length=20)),
                ('skill16', models.CharField(max_length=20)),
                ('skill17', models.CharField(max_length=20)),
                ('skill18', models.CharField(max_length=20)),
                ('skill19', models.CharField(max_length=20)),
                ('skill20', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'year_skills_vacancy',
            },
        ),
    ]
